#############################################################################
# Makefile for building: clipgrab
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Thu Sep 20 21:00:34 2018
# Project:  clipgrab.pro
# Template: app
# Command: $(QMAKE) -o Makefile clipgrab.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing  -DCLIPGRAB_VERSION=3.7.0 -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing  -DCLIPGRAB_VERSION=3.7.0 -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = clipgrab.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		mainwindow.h \
		video.h \
		video_youtube.h \
		video_dailymotion.h \
		video_vimeo.h \
		video_myspass.h \
		video_heuristic.h \
		video_facebook.h \
		http_handler.h \
		notifications.h \
		message_dialog.h
SOURCES = clipgrab.cpp \
		converter.cpp \
		converter_copy.cpp \
		converter_ffmpeg.cpp \
		main.cpp \
		mainwindow.cpp \
		video.cpp \
		video_youtube.cpp \
		video_dailymotion.cpp \
		video_vimeo.cpp \
		video_myspass.cpp \
		video_heuristic.cpp \
		video_facebook.cpp \
		http_handler.cpp \
		notifications.cpp \
		message_dialog.cpp
OBJECTS = clipgrab.o \
		converter.o \
		converter_copy.o \
		converter_ffmpeg.o \
		main.o \
		mainwindow.o \
		video.o \
		video_youtube.o \
		video_dailymotion.o \
		video_vimeo.o \
		video_myspass.o \
		video_heuristic.o \
		video_facebook.o \
		http_handler.o \
		notifications.o \
		message_dialog.o \
		mainwindow.o \
		metadata-dialog.o \
		update_message.o \
		message_dialog.o \
		login_dialog.o
FORMS = mainwindow.ui \
		metadata-dialog.ui \
		update_message.ui \
		message_dialog.ui \
		login_dialog.ui
UICDECLS = mainwindow.h \
		metadata-dialog.h \
		update_message.h \
		message_dialog.h \
		login_dialog.h
UICIMPLS = mainwindow.cpp \
		metadata-dialog.cpp \
		update_message.cpp \
		message_dialog.cpp \
		login_dialog.cpp
SRCMOC   = moc_clipgrab.cpp \
		moc_converter.cpp \
		moc_converter_copy.cpp \
		moc_converter_ffmpeg.cpp \
		moc_mainwindow.cpp \
		moc_video.cpp \
		moc_video_youtube.cpp \
		moc_video_dailymotion.cpp \
		moc_video_vimeo.cpp \
		moc_video_heuristic.cpp \
		moc_video_facebook.cpp \
		moc_http_handler.cpp \
		moc_message_dialog.cpp \
		moc_mainwindow.cpp \
		moc_metadata-dialog.cpp \
		moc_update_message.cpp \
		moc_message_dialog.cpp \
		moc_login_dialog.cpp
OBJMOC = moc_clipgrab.o \
		moc_converter.o \
		moc_converter_copy.o \
		moc_converter_ffmpeg.o \
		moc_mainwindow.o \
		moc_video.o \
		moc_video_youtube.o \
		moc_video_dailymotion.o \
		moc_video_vimeo.o \
		moc_video_heuristic.o \
		moc_video_facebook.o \
		moc_http_handler.o \
		moc_message_dialog.o \
		moc_mainwindow.o \
		moc_metadata-dialog.o \
		moc_update_message.o \
		moc_message_dialog.o \
		moc_login_dialog.o
DIST	   = clipgrab.pro
QMAKE_TARGET = clipgrab
DESTDIR  = 
TARGET   = clipgrab

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: clipgrab.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile clipgrab.pro
qmake: 
	@$(QMAKE) -o Makefile clipgrab.pro

dist: 
	@mkdir -p .tmp/clipgrab && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/clipgrab/ && $(COPY_FILE) --parents clipgrab_bg.ts clipgrab_ca.ts clipgrab_cs.ts clipgrab_de.ts clipgrab_el.ts clipgrab_es.ts clipgrab_eu.ts clipgrab_fa.ts clipgrab_fr.ts clipgrab_fi.ts clipgrab_hr.ts clipgrab_hu.ts clipgrab_id.ts clipgrab_it.ts clipgrab_ja.ts clipgrab_ko.ts clipgrab_mk.ts clipgrab_lt.ts clipgrab_nl.ts clipgrab_no.ts clipgrab_pl.ts clipgrab_pt.ts clipgrab_ro.ts clipgrab_ru.ts clipgrab_si.ts clipgrab_sv.ts clipgrab_sw.ts clipgrab_tr.ts clipgrab_vi.ts clipgrab_zh.ts clipgrab_strings.ts .tmp/clipgrab/ && ( cd `dirname .tmp/clipgrab` && $(TAR) clipgrab.tar clipgrab && $(GZIP) clipgrab.tar ) && $(MOVE) `dirname .tmp/clipgrab`/clipgrab.tar.gz . && $(DEL_FILE) -r .tmp/clipgrab

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

clipgrab.o: clipgrab.cpp clipgrab.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h

converter.o: converter.cpp converter.h

converter_copy.o: converter_copy.cpp converter_copy.h \
		converter.h

converter_ffmpeg.o: converter_ffmpeg.cpp converter_ffmpeg.h \
		converter.h

main.o: main.cpp mainwindow.h \
		clipgrab.h \
		notifications.h \
		savedialog_mac.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h \
		notifications_mac.h

mainwindow.o: mainwindow.cpp mainwindow.h \
		clipgrab.h \
		notifications.h \
		savedialog_mac.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h \
		notifications_mac.h \
		mainwindow.h

video.o: video.cpp video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_youtube.o: video_youtube.cpp video_youtube.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_dailymotion.o: video_dailymotion.cpp video_dailymotion.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_vimeo.o: video_vimeo.cpp video_vimeo.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_myspass.o: video_myspass.cpp video_myspass.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_heuristic.o: video_heuristic.cpp video_heuristic.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

video_facebook.o: video_facebook.cpp video_facebook.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

http_handler.o: http_handler.cpp http_handler.h

notifications.o: notifications.cpp notifications.h \
		notifications_mac.h

message_dialog.o: message_dialog.cpp message_dialog.h \
		message_dialog.h

mainwindow.h: mainwindow.ui 
	$(UIC) mainwindow.ui -o mainwindow.h

mainwindow.cpp: mainwindow.h mainwindow.ui 
	$(UIC) mainwindow.ui -i mainwindow.h -o mainwindow.cpp

metadata-dialog.h: metadata-dialog.ui 
	$(UIC) metadata-dialog.ui -o metadata-dialog.h

metadata-dialog.cpp: metadata-dialog.h metadata-dialog.ui 
	$(UIC) metadata-dialog.ui -i metadata-dialog.h -o metadata-dialog.cpp

update_message.h: update_message.ui 
	$(UIC) update_message.ui -o update_message.h

update_message.cpp: update_message.h update_message.ui 
	$(UIC) update_message.ui -i update_message.h -o update_message.cpp

message_dialog.h: message_dialog.ui 
	$(UIC) message_dialog.ui -o message_dialog.h

message_dialog.cpp: message_dialog.h message_dialog.ui 
	$(UIC) message_dialog.ui -i message_dialog.h -o message_dialog.cpp

login_dialog.h: login_dialog.ui 
	$(UIC) login_dialog.ui -o login_dialog.h

login_dialog.cpp: login_dialog.h login_dialog.ui 
	$(UIC) login_dialog.ui -i login_dialog.h -o login_dialog.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		clipgrab.h \
		notifications.h \
		savedialog_mac.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h \
		notifications_mac.h \
		mainwindow.h

metadata-dialog.o: metadata-dialog.cpp metadata-dialog.h

update_message.o: update_message.cpp update_message.h

message_dialog.o: message_dialog.cpp message_dialog.h \
		message_dialog.h

login_dialog.o: login_dialog.cpp login_dialog.h

moc_clipgrab.o: moc_clipgrab.cpp  clipgrab.h video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h

moc_converter.o: moc_converter.cpp  converter.h 

moc_converter_copy.o: moc_converter_copy.cpp  converter_copy.h converter.h

moc_converter_ffmpeg.o: moc_converter_ffmpeg.cpp  converter_ffmpeg.h converter.h

moc_mainwindow.o: moc_mainwindow.cpp  mainwindow.h clipgrab.h \
		notifications.h \
		savedialog_mac.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h \
		notifications_mac.h

moc_video.o: moc_video.cpp  video.h converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_video_youtube.o: moc_video_youtube.cpp  video_youtube.h video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_video_dailymotion.o: moc_video_dailymotion.cpp  video_dailymotion.h video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_video_vimeo.o: moc_video_vimeo.cpp  video_vimeo.h video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_video_heuristic.o: moc_video_heuristic.cpp  video_heuristic.h video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_video_facebook.o: moc_video_facebook.cpp  video_facebook.h video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h

moc_http_handler.o: moc_http_handler.cpp  http_handler.h 

moc_message_dialog.o: moc_message_dialog.cpp  message_dialog.h 

moc_mainwindow.o: moc_mainwindow.cpp  mainwindow.h clipgrab.h \
		notifications.h \
		savedialog_mac.h \
		video.h \
		video_youtube.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter.h \
		converter_copy.h \
		converter_ffmpeg.h \
		message_dialog.h \
		http_handler.h \
		notifications_mac.h

moc_metadata-dialog.o: moc_metadata-dialog.cpp  metadata-dialog.h 

moc_update_message.o: moc_update_message.cpp  update_message.h 

moc_message_dialog.o: moc_message_dialog.cpp  message_dialog.h 

moc_login_dialog.o: moc_login_dialog.cpp  login_dialog.h 

moc_clipgrab.cpp: $(MOC) clipgrab.h
	$(MOC) clipgrab.h -o moc_clipgrab.cpp

moc_converter.cpp: $(MOC) converter.h
	$(MOC) converter.h -o moc_converter.cpp

moc_converter_copy.cpp: $(MOC) converter_copy.h
	$(MOC) converter_copy.h -o moc_converter_copy.cpp

moc_converter_ffmpeg.cpp: $(MOC) converter_ffmpeg.h
	$(MOC) converter_ffmpeg.h -o moc_converter_ffmpeg.cpp

moc_mainwindow.cpp: $(MOC) mainwindow.h
	$(MOC) mainwindow.h -o moc_mainwindow.cpp

moc_video.cpp: $(MOC) video.h
	$(MOC) video.h -o moc_video.cpp

moc_video_youtube.cpp: $(MOC) video_youtube.h
	$(MOC) video_youtube.h -o moc_video_youtube.cpp

moc_video_dailymotion.cpp: $(MOC) video_dailymotion.h
	$(MOC) video_dailymotion.h -o moc_video_dailymotion.cpp

moc_video_vimeo.cpp: $(MOC) video_vimeo.h
	$(MOC) video_vimeo.h -o moc_video_vimeo.cpp

moc_video_heuristic.cpp: $(MOC) video_heuristic.h
	$(MOC) video_heuristic.h -o moc_video_heuristic.cpp

moc_video_facebook.cpp: $(MOC) video_facebook.h
	$(MOC) video_facebook.h -o moc_video_facebook.cpp

moc_http_handler.cpp: $(MOC) http_handler.h
	$(MOC) http_handler.h -o moc_http_handler.cpp

moc_message_dialog.cpp: $(MOC) message_dialog.h
	$(MOC) message_dialog.h -o moc_message_dialog.cpp

moc_mainwindow.cpp: $(MOC) mainwindow.h
	$(MOC) mainwindow.h -o moc_mainwindow.cpp

moc_metadata-dialog.cpp: $(MOC) metadata-dialog.h
	$(MOC) metadata-dialog.h -o moc_metadata-dialog.cpp

moc_update_message.cpp: $(MOC) update_message.h
	$(MOC) update_message.h -o moc_update_message.cpp

moc_message_dialog.cpp: $(MOC) message_dialog.h
	$(MOC) message_dialog.h -o moc_message_dialog.cpp

moc_login_dialog.cpp: $(MOC) login_dialog.h
	$(MOC) login_dialog.h -o moc_login_dialog.cpp

####### Install

install:  

uninstall:  

