#############################################################################
# Makefile for building: clipgrab
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sat Sep 22 21:59:01 2018
# Project:  clipgrab.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile clipgrab.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCLIPGRAB_VERSION=3.7.0 -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = clipgrab.cpp \
		converter.cpp \
		converter_copy.cpp \
		converter_ffmpeg.cpp \
		main.cpp \
		mainwindow.cpp \
		video.cpp \
		video_youtube.cpp \
		video_dailymotion.cpp \
		video_vimeo.cpp \
		video_myspass.cpp \
		video_heuristic.cpp \
		video_facebook.cpp \
		http_handler.cpp \
		notifications.cpp \
		message_dialog.cpp moc_clipgrab.cpp \
		moc_converter.cpp \
		moc_converter_copy.cpp \
		moc_converter_ffmpeg.cpp \
		moc_mainwindow.cpp \
		moc_video.cpp \
		moc_video_youtube.cpp \
		moc_video_dailymotion.cpp \
		moc_video_vimeo.cpp \
		moc_video_heuristic.cpp \
		moc_video_facebook.cpp \
		moc_http_handler.cpp \
		moc_message_dialog.cpp \
		qrc_resources.cpp
OBJECTS       = clipgrab.o \
		converter.o \
		converter_copy.o \
		converter_ffmpeg.o \
		main.o \
		mainwindow.o \
		video.o \
		video_youtube.o \
		video_dailymotion.o \
		video_vimeo.o \
		video_myspass.o \
		video_heuristic.o \
		video_facebook.o \
		http_handler.o \
		notifications.o \
		message_dialog.o \
		moc_clipgrab.o \
		moc_converter.o \
		moc_converter_copy.o \
		moc_converter_ffmpeg.o \
		moc_mainwindow.o \
		moc_video.o \
		moc_video_youtube.o \
		moc_video_dailymotion.o \
		moc_video_vimeo.o \
		moc_video_heuristic.o \
		moc_video_facebook.o \
		moc_http_handler.o \
		moc_message_dialog.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		clipgrab.pro
QMAKE_TARGET  = clipgrab
DESTDIR       = 
TARGET        = clipgrab

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_metadata-dialog.h ui_update_message.h ui_message_dialog.h ui_login_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: clipgrab.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile clipgrab.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile clipgrab.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/clipgrab3.7.0 || $(MKDIR) .tmp/clipgrab3.7.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/clipgrab3.7.0/ && $(COPY_FILE) --parents clipgrab.h converter.h converter_copy.h converter_ffmpeg.h mainwindow.h video.h video_youtube.h video_dailymotion.h video_vimeo.h video_myspass.h video_heuristic.h video_facebook.h http_handler.h notifications.h message_dialog.h .tmp/clipgrab3.7.0/ && $(COPY_FILE) --parents resources.qrc .tmp/clipgrab3.7.0/ && $(COPY_FILE) --parents clipgrab.cpp converter.cpp converter_copy.cpp converter_ffmpeg.cpp main.cpp mainwindow.cpp video.cpp video_youtube.cpp video_dailymotion.cpp video_vimeo.cpp video_myspass.cpp video_heuristic.cpp video_facebook.cpp http_handler.cpp notifications.cpp message_dialog.cpp .tmp/clipgrab3.7.0/ && $(COPY_FILE) --parents mainwindow.ui metadata-dialog.ui update_message.ui message_dialog.ui login_dialog.ui .tmp/clipgrab3.7.0/ && $(COPY_FILE) --parents clipgrab_bg.ts clipgrab_ca.ts clipgrab_cs.ts clipgrab_de.ts clipgrab_el.ts clipgrab_es.ts clipgrab_eu.ts clipgrab_fa.ts clipgrab_fr.ts clipgrab_fi.ts clipgrab_hr.ts clipgrab_hu.ts clipgrab_id.ts clipgrab_it.ts clipgrab_ja.ts clipgrab_ko.ts clipgrab_mk.ts clipgrab_lt.ts clipgrab_nl.ts clipgrab_no.ts clipgrab_pl.ts clipgrab_pt.ts clipgrab_ro.ts clipgrab_ru.ts clipgrab_si.ts clipgrab_sv.ts clipgrab_sw.ts clipgrab_tr.ts clipgrab_vi.ts clipgrab_zh.ts clipgrab_strings.ts .tmp/clipgrab3.7.0/ && (cd `dirname .tmp/clipgrab3.7.0` && $(TAR) clipgrab3.7.0.tar clipgrab3.7.0 && $(COMPRESS) clipgrab3.7.0.tar) && $(MOVE) `dirname .tmp/clipgrab3.7.0`/clipgrab3.7.0.tar.gz . && $(DEL_FILE) -r .tmp/clipgrab3.7.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_clipgrab.cpp moc_converter.cpp moc_converter_copy.cpp moc_converter_ffmpeg.cpp moc_mainwindow.cpp moc_video.cpp moc_video_youtube.cpp moc_video_dailymotion.cpp moc_video_vimeo.cpp moc_video_heuristic.cpp moc_video_facebook.cpp moc_http_handler.cpp moc_message_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clipgrab.cpp moc_converter.cpp moc_converter_copy.cpp moc_converter_ffmpeg.cpp moc_mainwindow.cpp moc_video.cpp moc_video_youtube.cpp moc_video_dailymotion.cpp moc_video_vimeo.cpp moc_video_heuristic.cpp moc_video_facebook.cpp moc_http_handler.cpp moc_message_dialog.cpp
moc_clipgrab.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_youtube.h \
		ui_login_dialog.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter_copy.h \
		ui_update_message.h \
		message_dialog.h \
		clipgrab.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) clipgrab.h -o moc_clipgrab.cpp

moc_converter.cpp: converter.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) converter.h -o moc_converter.cpp

moc_converter_copy.cpp: converter.h \
		converter_copy.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) converter_copy.h -o moc_converter_copy.cpp

moc_converter_ffmpeg.cpp: converter.h \
		converter_ffmpeg.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) converter_ffmpeg.h -o moc_converter_ffmpeg.cpp

moc_mainwindow.cpp: ui_mainwindow.h \
		ui_metadata-dialog.h \
		clipgrab.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_youtube.h \
		ui_login_dialog.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter_copy.h \
		ui_update_message.h \
		message_dialog.h \
		notifications.h \
		notifications_mac.h \
		savedialog_mac.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_video.cpp: converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video.h -o moc_video.cpp

moc_video_youtube.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h \
		video_youtube.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video_youtube.h -o moc_video_youtube.cpp

moc_video_dailymotion.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_dailymotion.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video_dailymotion.h -o moc_video_dailymotion.cpp

moc_video_vimeo.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h \
		video_vimeo.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video_vimeo.h -o moc_video_vimeo.cpp

moc_video_heuristic.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_heuristic.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video_heuristic.h -o moc_video_heuristic.cpp

moc_video_facebook.cpp: video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h \
		video_facebook.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) video_facebook.h -o moc_video_facebook.cpp

moc_http_handler.cpp: http_handler.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) http_handler.h -o moc_http_handler.cpp

moc_message_dialog.cpp: message_dialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) message_dialog.h -o moc_message_dialog.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		equifax_secure_ca.crt \
		clipgrab_bg.qm \
		clipgrab_fa.qm \
		clipgrab_si.qm \
		clipgrab_el.qm \
		clipgrab_tr.qm \
		clipgrab_pl.qm \
		clipgrab_no.qm \
		clipgrab_eu.qm \
		clipgrab_ro.qm \
		clipgrab_mk.qm \
		clipgrab_cs.qm \
		clipgrab_vi.qm \
		clipgrab_it.qm \
		clipgrab_pa.qm \
		clipgrab_sw.qm \
		clipgrab_hr.qm \
		clipgrab_fi.qm \
		clipgrab_zh.qm \
		clipgrab_hu.qm \
		clipgrab_sr.qm \
		clipgrab_lt.qm \
		clipgrab_pt.qm \
		clipgrab_sv.qm \
		clipgrab_de.qm \
		clipgrab_nl.qm \
		clipgrab_id.qm \
		clipgrab_ca.qm \
		clipgrab_es.qm \
		clipgrab_ja.qm \
		clipgrab_ru.qm \
		clipgrab_fr.qm \
		clipgrab_ko.qm \
		equifax_secure_ca.crt \
		splash.png \
		logo.png \
		icon.png \
		paypal-logo.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_metadata-dialog.h ui_update_message.h ui_message_dialog.h ui_login_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_metadata-dialog.h ui_update_message.h ui_message_dialog.h ui_login_dialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_metadata-dialog.h: metadata-dialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic metadata-dialog.ui -o ui_metadata-dialog.h

ui_update_message.h: update_message.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic update_message.ui -o ui_update_message.h

ui_message_dialog.h: message_dialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic message_dialog.ui -o ui_message_dialog.h

ui_login_dialog.h: login_dialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic login_dialog.ui -o ui_login_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

clipgrab.o: clipgrab.cpp clipgrab.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_youtube.h \
		ui_login_dialog.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter_copy.h \
		ui_update_message.h \
		message_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipgrab.o clipgrab.cpp

converter.o: converter.cpp converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o converter.cpp

converter_copy.o: converter_copy.cpp converter_copy.h \
		converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter_copy.o converter_copy.cpp

converter_ffmpeg.o: converter_ffmpeg.cpp converter_ffmpeg.h \
		converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter_ffmpeg.o converter_ffmpeg.cpp

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		ui_metadata-dialog.h \
		clipgrab.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_youtube.h \
		ui_login_dialog.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter_copy.h \
		ui_update_message.h \
		message_dialog.h \
		notifications.h \
		notifications_mac.h \
		savedialog_mac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		ui_metadata-dialog.h \
		clipgrab.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		video_youtube.h \
		ui_login_dialog.h \
		video_vimeo.h \
		video_dailymotion.h \
		video_myspass.h \
		video_facebook.h \
		video_heuristic.h \
		converter_copy.h \
		ui_update_message.h \
		message_dialog.h \
		notifications.h \
		notifications_mac.h \
		savedialog_mac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

video.o: video.cpp video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video.o video.cpp

video_youtube.o: video_youtube.cpp video_youtube.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_youtube.o video_youtube.cpp

video_dailymotion.o: video_dailymotion.cpp video_dailymotion.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_dailymotion.o video_dailymotion.cpp

video_vimeo.o: video_vimeo.cpp video_vimeo.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_vimeo.o video_vimeo.cpp

video_myspass.o: video_myspass.cpp video_myspass.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_myspass.o video_myspass.cpp

video_heuristic.o: video_heuristic.cpp video_heuristic.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_heuristic.o video_heuristic.cpp

video_facebook.o: video_facebook.cpp video_facebook.h \
		video.h \
		converter.h \
		converter_ffmpeg.h \
		http_handler.h \
		ui_login_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_facebook.o video_facebook.cpp

http_handler.o: http_handler.cpp http_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o http_handler.o http_handler.cpp

notifications.o: notifications.cpp notifications.h \
		notifications_mac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notifications.o notifications.cpp

message_dialog.o: message_dialog.cpp message_dialog.h \
		ui_message_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o message_dialog.o message_dialog.cpp

moc_clipgrab.o: moc_clipgrab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clipgrab.o moc_clipgrab.cpp

moc_converter.o: moc_converter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_converter.o moc_converter.cpp

moc_converter_copy.o: moc_converter_copy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_converter_copy.o moc_converter_copy.cpp

moc_converter_ffmpeg.o: moc_converter_ffmpeg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_converter_ffmpeg.o moc_converter_ffmpeg.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_video.o: moc_video.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video.o moc_video.cpp

moc_video_youtube.o: moc_video_youtube.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_youtube.o moc_video_youtube.cpp

moc_video_dailymotion.o: moc_video_dailymotion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_dailymotion.o moc_video_dailymotion.cpp

moc_video_vimeo.o: moc_video_vimeo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_vimeo.o moc_video_vimeo.cpp

moc_video_heuristic.o: moc_video_heuristic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_heuristic.o moc_video_heuristic.cpp

moc_video_facebook.o: moc_video_facebook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_facebook.o moc_video_facebook.cpp

moc_http_handler.o: moc_http_handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_http_handler.o moc_http_handler.cpp

moc_message_dialog.o: moc_message_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_message_dialog.o moc_message_dialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

